[package]
name = "dzip-core"
version = "0.3.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
bzip2 = "0.6.1"
flate2 = "1.1.8"
lzma-rs = "0.3.0"
thiserror = "2.0.18"
log = "0.4"
serde = { version = "1.0.228", features = ["derive"] }
